#!/usr/bin/env bash

set -eux

sudo sed -i "0,/.*PermitRootLogin.*/s//PermitRootLogin yes/" /etc/ssh/sshd_config

sudo cat <<EOF | sudo tee /etc/modules-load.d/crio.conf
overlay
br_netfilter
EOF

# Set up required sysctl params, these persist across reboots.
sudo cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
net.bridge.bridge-nf-call-iptables  = 1
net.ipv4.ip_forward                 = 1
net.bridge.bridge-nf-call-ip6tables = 1
EOF

sudo apt-get install -y kubelet kubeadm kubectl cri-o cri-tools linux-headers-"$(uname -r)"
sudo apt-mark hold kubelet kubeadm kubectl cri-o cri-tools

sudo systemctl enable crio
sudo systemctl enable kubelet
